{% set name = "rabpro" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/veinsoftheearth/rabpro/archive/v{{ version }}.tar.gz
  sha256: 62bb308829b48a36d2349e0d9d6c5b0ce3959423d976c9278f2c5b43ac92b54a
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.  

build:
  noarch: python
  number: 0  
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:  
  host:
    - pip
    - python >=3.7
    
  
  run:
    - python >=3.7,<3.10
    - numpy
    - geopandas >=0.7.0
    - scikit-image
    - pyproj >2.2.0
    - shapely
    - requests
    - appdirs
    - gdown
    - tqdm
    - colorama
    - beautifulsoup4
    - earthengine-api

test:  
  imports:
  - rabpro

about:
  home: https://github.com/VeinsOfTheEarth/rabpro  
  license: BSD-3-Clause
  license_family: BSD  
  license_file: LICENSE.txt
  summary: 'Package to delineate subbasins and compute statistics.'  
  description: |
    rabpro computes longitudinal river profiles,
    global watershed delineation, watershed stats.    
  doc_url: https://veinsoftheearth.github.io/rabpro
  dev_url: https://github.com/VeinsOfTheEarth/rabpro
extra:
  recipe-maintainers:    
    - jsta
    - jonschwenk
